name: Publish Docker image
on:
  push:
    branches: [ enable_multiarch_build ]
jobs:
  build_amd64:
    name: Build amd64 docker image
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Get Version
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ci/Dockerfile
          tags: luxonis/depthai-library:${{ steps.vars.outputs.short_ref }}
  build_armv7:
    name: Build armv7 docker image
    runs-on: luxonis-armhf
    timeout-minutes: 240
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Get Version
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ci/Dockerfile
          tags: luxonis/depthai-library:${{ steps.vars.outputs.short_ref }}
  build_armv8:
    name: Build armv8 docker image
    runs-on: ARM64
    timeout-minutes: 240
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Get Version
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ci/Dockerfile
          tags: luxonis/depthai-library:${{ steps.vars.outputs.short_ref }}
